In [1]:
import sqlite3
from sqlite3 import Error
 

def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
    except Error as e:
        print(e)
 
    return conn

In [2]:
def select_option1(conn):
    """
    1. The branch 2 was established in the year.
    """
    cur = conn.cursor()
    print("DateYear")
    cur.execute("""SELECT DateYear
                FROM Branch
                WHERE ID = 2;""")
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row[0])

In [3]:
def select_option2(conn):
    """
    2. The number of members who have subscribed to half-yearly plans in branch 4.
    """
    cur = conn.cursor()
    print("Count")
    cur.execute("""SELECT count(*)
                FROM Billing 
                LEFT JOIN Subscription ON Billing.SubscriptionID = Subscription.ID
                LEFT JOIN Member ON Billing.MemberID = Member.ID
                WHERE DurationMonths = 6 and BranchID = 4;""")
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row[0])

In [4]:
def select_option3(conn):
    """
    3. The membership fee for a member with a yearly plan who has opted for the individual package.
    """
    cur = conn.cursor()
    print("MembershipFee")
    cur.execute("""SELECT MemberFee1 
                FROM Temp
                WHERE Name1 = "Individual"
                AND DurationMonths1 = 12
                AND MemberID1 = 4;""")
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row[0])

In [5]:
def select_option4(conn):
    """
    4. The number of trainers who have experience of 3 years and above.
    """
    cur = conn.cursor()
    print("Count")
    cur.execute("""SELECT COUNT(*)
                FROM Employee
                WHERE Specialization = "Trainer"
                AND Experience >= 3;""")
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row[0])

In [6]:
def select_option5(conn):
    """
    5. The count of students/regular citizens/ senior citizens.
    """
    cur = conn.cursor()
    print("Status,Count")
    cur.execute("""SELECT Status, COUNT(Status)
                FROM Member
                GROUP BY Status;""")
 
    rows = cur.fetchall()
    for row in rows:
        print(row[0],row[1])

In [7]:
def select_option6(conn):
    """
    6. The total number of male and female members in each branch.
    """
    cur = conn.cursor()
    print("BranchID, Gender, Count")
    cur.execute("""SELECT BranchID, Gender, COUNT(Gender)
                FROM Member
                GROUP BY BranchID, Gender;""")
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row[0],row[1],row[2])

In [8]:
def select_option7(conn):
    """
    7. The gross income of the organization.
    """
    cur = conn.cursor()
    print("Gross Income")
    cur.execute("""SELECT SUM(MemberFee)
                FROM Billing
                WHERE StartDateYear = 2013;""")
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row[0])

In [9]:
def select_option8(conn):
    """
    8. The contact details of each branch.
    """
    cur = conn.cursor()
    print("ID, ContactPhone, ContactEmail")
    cur.execute("""SELECT ID, ContactPhone, ContactEmail
                FROM Branch;""")
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row[0],row[1],row[2])

In [10]:
def select_option9(conn):
    """
    9. The maximum weight of a member among all the members and his calculated BMI.
    """
    cur = conn.cursor()
    print("Weight, BMI")
    cur.execute("""SELECT MAX(Weight), BMI 
                FROM Member;""")
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row[0],row[1])

In [11]:
def select_option10(conn):
    """
    10. The number of members who have booked a 5:00 pm slot for Zumba on 12/08/2013.
    """
    cur = conn.cursor()
    print("Count")
    cur.execute("""SELECT COUNT(*) 
                FROM Booking 
                WHERE Class = "Zumba" 
                AND DateMonth = 8 
                AND DateDay = 12 
                AND DateYear = 2013
                AND StartTimeHour = 17
                AND StartTimeMin = 00;""")
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row[0])

In [12]:
def select_option11(conn):
    """
    11.  Inserting new record into Employee table.
    """
    Name = input("Enter the Name of the Employee : ")
    Specialization = input("Enter the Specialization of the Employee : ")
    Experience = input("Enter the Experience of the Employee : ")
    JoinDateYear = input("Enter the JoinDateYear of the Employee : ")
    JoinDateMonth = input("Enter the JoinDateMonth (Number) of the Employee : ")
    JoinDateDay = input("Enter the JoinDateDay of the Employee : ")
    ContactEmail = input("Enter the ContactEmail of the Employee : ")
    ContactPhone = input("Enter the ContactPhone of the Employee : ")
    SalaryID = input("Enter the SalaryID of the Employee : ")


    cur = conn.cursor()
    cur.execute("""INSERT INTO Employee(Name, Specialization, Experience, JoinDateYear, JoinDateMonth, JoinDateDay, ContactEmail, ContactPhone ,SalaryID) 
                VALUES(?,?,?,?,?,?,?,?,?);""",(Name,Specialization,Experience,JoinDateYear,JoinDateMonth,JoinDateDay,ContactEmail,ContactPhone,SalaryID))
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)

In [13]:
def select_option12(conn):
    """
    12. Updating Employee Table.
    """
    count = 0
    ID = input("Enter the Employee ID of the employee who's details are to be updated (Please ensure to enter the right ID): ")
    
    cur = conn.cursor()
    cur.execute("""SELECT EXISTS(SELECT * FROM Employee WHERE ID=? LIMIT 1);""",(ID,))
    exist = cur.fetchall()
    for exi in exist:
        if exi[0] == 1: 
            z = input("""Welcome to employee detail updation:
                  1. To update the Name of the employee, press 1
                  2. To update the Specialization of the employee, press 2
                  3. To update the Experience of the employee, press 3
                  4. To update the JoinDateYear of the employee, press 4
                  5. To update the JoinDateMonth of the employee, press 5
                  6. To update the JoinDateDay of the employee, press 6
                  7. To update the ContactEmail of the employee, press 7
                  8. To update the ContactPhone of the employee, press 8
                  9. To update the SalaryID of the employee, press 9\n""") 

        #    cur = conn.cursor()

            if z == '1':
                NewName = input("Enter the new Name of the employee: ")
                cur.execute("""UPDATE Employee SET Name = ? WHERE ID = ?;""",(NewName,ID))

            elif z == '2':
                NewSpecialization = input("Enter the new Specialization of the employee: ")
                cur.execute("""UPDATE Employee SET Specialization = ? WHERE ID = ?;""",(NewSpecialization,ID))

            elif z == '3':
                NewExperience = input("Enter the new Experience of the employee: ")
                cur.execute("""UPDATE Employee SET Experience = ? WHERE ID = ?;""",(NewExperience,ID))

            elif z == '4':
                NewJoinDateYear = input("Enter the new JoinDateYear of the employee: ")
                cur.execute("""UPDATE Employee SET JoinDateYear = ? WHERE ID = ?;""",(NewJoinDateYear,ID))

            elif z == '5':
                NewJoinDateMonth = input("Enter the new JoinDateMonth (Number) of the employee: ")
                cur.execute("""UPDATE Employee SET JoinDateMonth = ? WHERE ID = ?;""",(NewJoinDateMonth,ID))

            elif z == '6':
                NewJoinDateDay = input("Enter the new JoinDateDay of the employee: ")
                cur.execute("""UPDATE Employee SET JoinDateDay = ? WHERE ID = ?;""",(NewJoinDateDay,ID))

            elif z == '7':
                NewContactEmail = input("Enter the new ContactEmail of the employee: ")
                cur.execute("""UPDATE Employee SET ContactEmail = ? WHERE ID = ?;""",(NewContactEmail,ID))

            elif z == '8':
                NewContactPhone = input("Enter the new ContactPhone of the employee: ")
                cur.execute("""UPDATE Employee SET ContactPhone = ? WHERE ID = ?;""",(NewContactPhone,ID))

            elif z == '9':
                NewSalaryID = input("Enter the new SalaryID of the employee: ")
                cur.execute("""UPDATE Employee SET SalaryID = ? WHERE ID = ?;""",(NewSalaryID,ID))

            else:
                print("Invalid option")

            rows = cur.fetchall()

            for row in rows:
                print(row)
                
        else:
            print("""\n This is not a valid ID of the employee. \n""")

In [14]:
def select_option13(conn):
    """
    13. Deleting record from Employee Table.
    """
    count = 0
    ID = input("Enter the Employee ID of the employee who's details are to be deleted (Please ensure to enter the right ID) : ")

    cur = conn.cursor()
    cur.execute("""SELECT EXISTS(SELECT * FROM Employee WHERE ID=? LIMIT 1);""",(ID,))
    exist = cur.fetchall()
    for exi in exist:
        if exi[0] == 1:
            cur.execute("""DELETE FROM Employee WHERE ID = ?;""",(ID,))
            cur.execute("""DELETE FROM SQLITE_SEQUENCE WHERE NAME = "Employee";""")
            print("""\n This ID has been deleted. \n""")
            rows = cur.fetchall()
            for row in rows:
                print(row)
        else:
            print("""\n This is not a valid ID of the employee. \n""")

In [15]:
def select_option14(conn):
    """
    14. The entire Employee table records.
    """
    cur = conn.cursor()
    print("ID, Name, Specialization, Experience, JoinDateYear, JoinDateMonth, JoinDateDay, ContactEmail, ContactPhone, SalaryID")
    cur.execute("""SELECT *
                FROM Employee;""")
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)

In [16]:
def main():
    database = r"C:\databases\Fitness.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn:
        while 1:
            print("""\n Welcome to the Rhaegal Fitness Center database application:
            1. To know the year in which the branch 2 was established, Press 1
            2. To see the number of members who have subscribed to half-yearly plans in branch 4, Press 2
            3. To find the membership fee for a member with a yearly plan who has opted for the individual package, Press 3
            4. To know how many of the trainers have experience of 3 years and above, Press 4
            5. To see the count of students/regular citizens/ senior citizens, Press 5
            6. To see the total number of male and female members in each branch, Press 6
            7. To see the gross income of the organization, Press 7
            8. To see the contact details of each branch, Press 8
            9. To see the maximum weight of a member among all the members and his calculated BMI, Press 9
            10. To see the number of members who have booked a 5:00 pm slot for Zumba on 12/08/2013, Press 10
            11. To modify the Employees table, press 11
            12 to exit from the application press 12\n""")
            x = input()
            if x == '1':
                print("\n1. The year in which Branch 2 was established is")
                select_option1(conn)

            elif x == '2':
                print("\n2. The the number of members who have subscribed to half-yearly plans in branch 4")
                select_option2(conn)

            elif x == '3':
                print("\n3. The membership fee for a member with a yearly plan who has opted for the individual package")
                select_option3(conn)

            elif x == '4':
                print("\n4. The number of trainers who have experience of 3 years and above")
                select_option4(conn)

            elif x == '5':
                print("\n5. The count of students/regular citizens/ senior citizens")
                select_option5(conn)

            elif x == '6':
                print("\n6. The total number of male and female members in each branch")
                select_option6(conn)

            elif x == '7':
                print("\n7. The gross income of the organization")
                select_option7(conn)

            elif x == '8':
                print("\n8. The contact details of each branch")
                select_option8(conn)

            elif x == '9':
                print("\n9. The maximum weight of a member among all the members and his calculated BMI")
                select_option9(conn)

            elif x == '10':
                print("\n10. The number of members who have booked a 5:00 pm slot for Zumba on 12/08/2013")
                select_option10(conn)

            elif x == '11':
                while 1:
                    print("""\n Welcome to Employee table modification:
                          1.To insert new employee information, press 1
                          2.To update an employee information, press 2
                          3.To delete an employee information, press 3
                          4.To view the entire employee table post modification, press 4
                          5.To go to the main menu, press 5\n""")

                    y = input()
                    if y == '1':
                        select_option11(conn)
                    elif y == '2':
                        select_option12(conn)
                    elif y == '3':
                        select_option13(conn)
                    elif y == '4':
                        select_option14(conn)
                    elif y == '5':
                        break
                    else: 
                        print("The key pressed is invalid.")

            elif x == '12':
                print("Thank you")
                break
            else :
                print("The key pressed is invalid.")




if __name__ == '__main__':
    main()

 Welcome to the Rhaegal Fitness Center database application:
            1. To know the year in which the branch 2 was established, Press 1
            2. To see the number of members who have subscribed to half-yearly plans in branch 4, Press 2
            3. To find the membership fee for a member with a yearly plan who has opted for the individual package, Press 3
            4. To know how many of the trainers have experience of 3 years and above, Press 4
            5. To see the count of students/regular citizens/ senior citizens, Press 5
            6. To see the total number of male and female members in each branch, Press 6
            7. To see the gross income of the organization, Press 7
            8. To see the contact details of each branch, Press 8
            9. To see the maximum weight of a member among all the members and his calculated BMI, Press 9
            10. To see the number of members who have booked a 5:00 pm slot for Zumba on 12/08/2013, Press 10
            11. To modify the Employees table, press 11
            12 to exit from the application press 12

12
Thank you